find_package(glm REQUIRED)
find_package(SDL2 REQUIRED)
find_package(GLEW REQUIRED)
find_package(OpenGL REQUIRED)
find_package(GTest REQUIRED)
find_package(Boost REQUIRED)
find_package(range-v3 REQUIRED)